import 'dart:convert';
import 'dart:io';

/// Regenerates Flutter localizations and the small stable-key lookup adapter.
/// Run from apps/mobile: dart run tool/localizations.dart
Future<void> main() async {
  final result = await Process.run('flutter', ['gen-l10n']);
  stdout.write(result.stdout);
  stderr.write(result.stderr);
  if (result.exitCode != 0) {
    exitCode = result.exitCode;
    return;
  }
  final arb =
      jsonDecode(File('lib/l10n/app_en.arb').readAsStringSync())
          as Map<String, dynamic>;
  final output = StringBuffer(
    '// Generated by tool/localizations.dart. Do not edit by hand.\n'
    '// Preserves stable keys used by dynamic menus and status labels.\n'
    "import 'app_localizations.dart';\n\n"
    'String? lookupString(AppLocalizations strings, String key) => switch (key) {\n',
  );
  for (final key in arb.keys.where((key) => !key.startsWith('@'))) {
    final metadata = arb['@$key'] as Map<String, dynamic>?;
    final placeholders = metadata?['placeholders'] as Map<String, dynamic>?;
    final arguments = placeholders?.keys.map((name) => "'{$name}'").join(', ');
    final call = arguments == null || arguments.isEmpty
        ? 'strings.$key'
        : 'strings.$key($arguments)';
    output.writeln("  '$key' => $call,");
  }
  output.writeln('  _ => null,\n};');
  final path = 'lib/l10n/generated/lookup.dart';
  File(path).writeAsStringSync(output.toString());
  final format = await Process.run('dart', ['format', path]);
  stdout.write(format.stdout);
  stderr.write(format.stderr);
  exitCode = format.exitCode;
}
