pub mod activity;
pub mod attachment;
pub mod browser;
pub mod computer;
mod config;
pub mod connection;
pub mod conversation;
mod credential;
pub mod database;
pub mod dispatch;
pub mod external_browser;
pub mod file_browser;
mod files;
mod git;
pub mod host;
mod ids;
pub mod media;
mod message;
pub mod notification;
pub mod office;
pub mod plugin;
pub mod process;
pub mod projects;
pub mod role;
pub mod ssh;
pub mod terminal;
pub mod tool;
pub mod usage;

pub use config::*;
pub use credential::*;
pub use files::*;
pub use git::*;
pub use host::*;
pub use ids::*;
pub use message::*;

pub const VERSION: u16 = 1;
pub const MAX_FRAME_BYTES: usize = 16 * 1024 * 1024;
