[package]
name = "sailry-client"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
license.workspace = true

[dependencies]
sailry-protocol.workspace = true
sailry-link.workspace = true
tokio.workspace = true
serde = { workspace = true, features = ["rc"] }
serde_json.workspace = true
blake3.workspace = true

[dev-dependencies]
tokio.workspace = true
