//! Embedded product SVGs compose with Kit's own assets.
use gpui_kit::{AssetSource, Result, SharedString};
use std::borrow::Cow;

pub(crate) mod icons;

pub(crate) struct Assets;

pub(crate) const DRAG_ICON: &str = "icons/reicon/move.svg";

// Kit b79f4ce has no file-diff or Git status glyphs. These product SVGs use
// Kit Icon rendering, semantic colors and sizing; they are not custom controls.
// Kit b79f4ce also lacks save, cut and paste glyphs; use product SVGs through Kit Icon.
// Kit b79f4ce lacks permission shields; use unchanged Reicon Outline assets via Kit Icon.
// Kit b79f4ce has no microphone glyph; use the unchanged Reicon asset through Kit Icon.
// Kit b79f4ce lacks mirror glyphs; use product SVGs through Kit Icon.
// Kit b79f4ce has no drag handle; use Reicon’s original four-arrow glyph with the grab cursor.
const ICONS: &[(&str, &[u8])] = &[
    (
        "branding/sailry-mark.svg",
        include_bytes!("../../../assets/branding/sailry-mark.svg"),
    ),
    (
        "icons/remix/progress-2-line.svg",
        include_bytes!("../../../assets/icons/remix/progress-2-line.svg"),
    ),
    (
        "icons/remix/progress-4-line.svg",
        include_bytes!("../../../assets/icons/remix/progress-4-line.svg"),
    ),
    (
        "icons/remix/progress-6-line.svg",
        include_bytes!("../../../assets/icons/remix/progress-6-line.svg"),
    ),
    (
        "icons/remix/checkbox-blank-circle-line.svg",
        include_bytes!("../../../assets/icons/remix/checkbox-blank-circle-line.svg"),
    ),
    (
        "icons/remix/close-circle-line.svg",
        include_bytes!("../../../assets/icons/remix/close-circle-line.svg"),
    ),
    (
        "icons/files/word.svg",
        include_bytes!("../../../assets/icons/files/word.svg"),
    ),
    (
        "icons/files/excel.svg",
        include_bytes!("../../../assets/icons/files/excel.svg"),
    ),
    (
        "icons/files/powerpoint.svg",
        include_bytes!("../../../assets/icons/files/powerpoint.svg"),
    ),
    (
        "icons/files/pdf.svg",
        include_bytes!("../../../assets/icons/files/pdf.svg"),
    ),
    (
        "icons/reicon/gift.svg",
        include_bytes!("../../../assets/icons/reicon/gift.svg"),
    ),
    (
        "icons/reicon/receipt.svg",
        include_bytes!("../../../assets/icons/reicon/receipt.svg"),
    ),
    (
        "icons/reicon/cart.svg",
        include_bytes!("../../../assets/icons/reicon/cart.svg"),
    ),
    (
        "icons/reicon/handshake.svg",
        include_bytes!("../../../assets/icons/reicon/handshake.svg"),
    ),
    (
        DRAG_ICON,
        include_bytes!("../../../assets/icons/reicon/move.svg"),
    ),
    (
        "icons/flip-horizontal.svg",
        include_bytes!("../../../assets/icons/flip-horizontal.svg"),
    ),
    (
        "icons/flip-vertical.svg",
        include_bytes!("../../../assets/icons/flip-vertical.svg"),
    ),
    (
        "icons/reicon/microphone.svg",
        include_bytes!("../../../assets/icons/reicon/microphone.svg"),
    ),
    (
        "icons/providers/opencode.svg",
        include_bytes!("../../../assets/icons/providers/opencode.svg"),
    ),
    (
        "icons/providers/openai.svg",
        include_bytes!("../../../assets/icons/providers/openai.svg"),
    ),
    (
        "icons/providers/anthropic.svg",
        include_bytes!("../../../assets/icons/providers/anthropic.svg"),
    ),
    (
        "icons/providers/gemini.svg",
        include_bytes!("../../../assets/icons/providers/gemini.svg"),
    ),
    (
        "icons/providers/xai.svg",
        include_bytes!("../../../assets/icons/providers/xai.svg"),
    ),
    (
        "icons/providers/deepseek.svg",
        include_bytes!("../../../assets/icons/providers/deepseek.svg"),
    ),
    (
        "icons/providers/qwen.svg",
        include_bytes!("../../../assets/icons/providers/qwen.svg"),
    ),
    (
        "icons/providers/kimi.svg",
        include_bytes!("../../../assets/icons/providers/kimi.svg"),
    ),
    (
        "icons/providers/mistral.svg",
        include_bytes!("../../../assets/icons/providers/mistral.svg"),
    ),
    (
        "icons/providers/minimax.svg",
        include_bytes!("../../../assets/icons/providers/minimax.svg"),
    ),
    (
        "icons/providers/doubao.svg",
        include_bytes!("../../../assets/icons/providers/doubao.svg"),
    ),
    (
        "icons/providers/zai.svg",
        include_bytes!("../../../assets/icons/providers/zai.svg"),
    ),
    (
        "icons/providers/wenxin.svg",
        include_bytes!("../../../assets/icons/providers/wenxin.svg"),
    ),
    (
        "icons/providers/cohere.svg",
        include_bytes!("../../../assets/icons/providers/cohere.svg"),
    ),
    (
        "icons/reicon/shield.svg",
        include_bytes!("../../../assets/icons/reicon/shield.svg"),
    ),
    (
        "icons/reicon/shield-off.svg",
        include_bytes!("../../../assets/icons/reicon/shield-off.svg"),
    ),
    (
        "icons/os/android.svg",
        include_bytes!("../../../assets/icons/os/android.svg"),
    ),
    (
        "icons/os/apple.svg",
        include_bytes!("../../../assets/icons/os/apple.svg"),
    ),
    (
        "icons/os/windows11.svg",
        include_bytes!("../../../assets/icons/os/windows11.svg"),
    ),
    (
        "icons/os/linux.svg",
        include_bytes!("../../../assets/icons/os/linux.svg"),
    ),
    (
        "icons/fluent/document.svg",
        include_bytes!("../../../assets/icons/fluent/document.svg"),
    ),
    (
        "icons/fluent/document_text.svg",
        include_bytes!("../../../assets/icons/fluent/document_text.svg"),
    ),
    (
        "icons/fluent/code_block.svg",
        include_bytes!("../../../assets/icons/fluent/code_block.svg"),
    ),
    (
        "icons/fluent/table.svg",
        include_bytes!("../../../assets/icons/fluent/table.svg"),
    ),
    (
        "icons/fluent/slide_text_sparkle.svg",
        include_bytes!("../../../assets/icons/fluent/slide_text_sparkle.svg"),
    ),
    (
        "icons/fluent/document_folder.svg",
        include_bytes!("../../../assets/icons/fluent/document_folder.svg"),
    ),
    (
        "icons/save.svg",
        include_bytes!("../../../assets/icons/save.svg"),
    ),
    (
        "icons/cut.svg",
        include_bytes!("../../../assets/icons/cut.svg"),
    ),
    (
        "icons/paste.svg",
        include_bytes!("../../../assets/icons/paste.svg"),
    ),
    (
        "icons/git-added.svg",
        include_bytes!("../../../assets/icons/git-added.svg"),
    ),
    (
        "icons/git-modified.svg",
        include_bytes!("../../../assets/icons/git-modified.svg"),
    ),
    (
        "icons/git-deleted.svg",
        include_bytes!("../../../assets/icons/git-deleted.svg"),
    ),
    (
        "icons/git-renamed.svg",
        include_bytes!("../../../assets/icons/git-renamed.svg"),
    ),
    (
        "icons/git-conflict.svg",
        include_bytes!("../../../assets/icons/git-conflict.svg"),
    ),
    (
        "icons/file-diff.svg",
        include_bytes!("../../../assets/icons/file-diff.svg"),
    ),
    (
        "icons/reicon/accessibility.svg",
        include_bytes!("../../../assets/icons/reicon/accessibility.svg"),
    ),
    (
        "icons/reicon/screen-recording.svg",
        include_bytes!("../../../assets/icons/reicon/screen-recording.svg"),
    ),
    (
        "icons/reicon/smartphone.svg",
        include_bytes!("../../../assets/icons/reicon/smartphone.svg"),
    ),
    (
        "icons/reicon/help-circle.svg",
        include_bytes!("../../../assets/icons/reicon/help-circle.svg"),
    ),
    (
        "icons/reicon/paperclip.svg",
        include_bytes!("../../../assets/icons/reicon/paperclip.svg"),
    ),
    (
        "icons/reicon/folder.svg",
        include_bytes!("../../../assets/icons/reicon/folder.svg"),
    ),
    (
        "icons/reicon/code.svg",
        include_bytes!("../../../assets/icons/reicon/code.svg"),
    ),
    (
        "icons/reicon/terminal.svg",
        include_bytes!("../../../assets/icons/reicon/terminal.svg"),
    ),
    (
        "icons/reicon/globe.svg",
        include_bytes!("../../../assets/icons/reicon/globe.svg"),
    ),
    (
        "icons/reicon/server.svg",
        include_bytes!("../../../assets/icons/reicon/server.svg"),
    ),
    (
        "icons/reicon/database.svg",
        include_bytes!("../../../assets/icons/reicon/database.svg"),
    ),
    (
        "icons/reicon/package.svg",
        include_bytes!("../../../assets/icons/reicon/package.svg"),
    ),
    (
        "icons/reicon/game.svg",
        include_bytes!("../../../assets/icons/reicon/game.svg"),
    ),
    (
        "icons/reicon/book.svg",
        include_bytes!("../../../assets/icons/reicon/book.svg"),
    ),
    (
        "icons/reicon/finance.svg",
        include_bytes!("../../../assets/icons/reicon/finance.svg"),
    ),
    (
        "icons/reicon/device.svg",
        include_bytes!("../../../assets/icons/reicon/device.svg"),
    ),
    (
        "icons/reicon/education.svg",
        include_bytes!("../../../assets/icons/reicon/education.svg"),
    ),
    (
        "icons/reicon/writing.svg",
        include_bytes!("../../../assets/icons/reicon/writing.svg"),
    ),
    (
        "icons/reicon/tags.svg",
        include_bytes!("../../../assets/icons/reicon/tags.svg"),
    ),
    (
        "icons/reicon/music.svg",
        include_bytes!("../../../assets/icons/reicon/music.svg"),
    ),
    (
        "icons/reicon/media.svg",
        include_bytes!("../../../assets/icons/reicon/media.svg"),
    ),
    (
        "icons/reicon/design.svg",
        include_bytes!("../../../assets/icons/reicon/design.svg"),
    ),
    (
        "icons/reicon/health.svg",
        include_bytes!("../../../assets/icons/reicon/health.svg"),
    ),
    (
        "icons/reicon/nature.svg",
        include_bytes!("../../../assets/icons/reicon/nature.svg"),
    ),
    (
        "icons/reicon/business.svg",
        include_bytes!("../../../assets/icons/reicon/business.svg"),
    ),
    (
        "icons/reicon/analytics.svg",
        include_bytes!("../../../assets/icons/reicon/analytics.svg"),
    ),
    (
        "icons/reicon/profile.svg",
        include_bytes!("../../../assets/icons/reicon/profile.svg"),
    ),
    (
        "icons/reicon/fitness.svg",
        include_bytes!("../../../assets/icons/reicon/fitness.svg"),
    ),
    (
        "icons/reicon/law.svg",
        include_bytes!("../../../assets/icons/reicon/law.svg"),
    ),
    (
        "icons/reicon/audio.svg",
        include_bytes!("../../../assets/icons/reicon/audio.svg"),
    ),
    (
        "icons/reicon/travel.svg",
        include_bytes!("../../../assets/icons/reicon/travel.svg"),
    ),
    (
        "icons/reicon/tools.svg",
        include_bytes!("../../../assets/icons/reicon/tools.svg"),
    ),
    (
        "icons/reicon/science.svg",
        include_bytes!("../../../assets/icons/reicon/science.svg"),
    ),
    (
        "icons/reicon/ai.svg",
        include_bytes!("../../../assets/icons/reicon/ai.svg"),
    ),
    (
        "icons/reicon/favorite.svg",
        include_bytes!("../../../assets/icons/reicon/favorite.svg"),
    ),
];

impl AssetSource for Assets {
    fn load(&self, path: &str) -> Result<Option<Cow<'static, [u8]>>> {
        if let Some((_, bytes)) = ICONS.iter().find(|(name, _)| *name == path) {
            return Ok(Some(Cow::Borrowed(bytes)));
        }
        if let Some(bytes) = icons::load(path) {
            return Ok(Some(Cow::Owned(bytes)));
        }
        gpui_kit::assets::Assets.load(path)
    }

    fn list(&self, path: &str) -> Result<Vec<SharedString>> {
        let mut names = gpui_kit::assets::Assets.list(path)?;
        names.extend(
            ICONS
                .iter()
                .filter(|(name, _)| name.starts_with(path))
                .map(|(name, _)| (*name).into()),
        );
        names.extend(icons::list(path));
        Ok(names)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn embedded_product_icons() {
        assert!(Assets.load("icons/folder.svg").unwrap().is_some());
    }
}
