// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'commands.dart';
import 'conversation.dart';
import 'login.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'ports.dart';
import 'terminal.dart';
import 'transfers/download.dart';
import 'transfers/upload.dart';
import 'usage.dart';

// These functions are ignored because they are not marked as `pub`: `new`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `drop`, `drop`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Connection>>
abstract class Connection implements RustOpaqueInterface {
  Future<void> close();

  /// Partial bytes are unverified until Download.next returns None successfully.
  Future<Download> downloadAttachment({required String download});

  /// Adapt a project file descriptor to the same verified download stream.
  Future<Download> downloadFile({required String download});

  Future<String> execute({required String request});

  /// Bind a controller loopback port using the shared authenticated Client.
  Future<Forwarding> forwardPort({
    required int remotePort,
    required int localPort,
  });

  Future<Forwarding> forwardService({
    required String source,
    required int localPort,
  });

  /// Keep this serialized request unchanged when retrying an uncertain result.
  Future<String> prepare({required String command});

  /// Search committed text through the shared Client; closing cancels this read-only query.
  Future<String> searchConversation({
    required String session,
    required String query,
  });

  /// Adapt a Node upload descriptor to bounded byte writes; this does not publish it.
  Future<Upload> uploadAttachment({required String upload});

  Future<Updates> watch();

  Future<CommandUpdates> watchCommands({required String session});

  Future<ConversationUpdates> watchConversation({required String session});

  /// Observe an existing attempt; BeginProviderLogin remains an explicit durable command.
  Future<LoginUpdates> watchLogin({required String attempt});

  /// Observe an existing MCP OAuth attempt without initiating authorization.
  Future<LoginUpdates> watchMcpLogin({required String attempt});

  Future<TerminalUpdates> watchTerminal({required String terminal});

  Future<UsageUpdates> watchUsage({required String query});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Updates>>
abstract class Updates implements RustOpaqueInterface {
  Future<void> close();

  Future<String> next();
}
