// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `drop`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SpeechInput>>
abstract class SpeechInput implements RustOpaqueInterface {
  Future<void> cancel();

  Future<void> download();

  Future<int> downloadProgress();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  /// Pass this controller's application-support directory, not an execution Node profile.
  static Future<SpeechInput> newInstance({required String directory}) =>
      RustLib.instance.api.crateApiSpeechSpeechInputNew(directory: directory);

  Future<bool> ready();

  /// Mono floating-point PCM; language is auto, zh, or en. Does not send a message.
  Future<String> transcribe({
    required List<double> samples,
    required int sampleRate,
    required String language,
  });
}
