// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `check_chunk`, `closed`, `result`, `spawn`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Transfer`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `drop`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Digest>>
abstract class Digest implements RustOpaqueInterface {
  static Future<Digest> default_() =>
      RustLib.instance.api.crateApiTransfersDigestDefault();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<Digest> newInstance() =>
      RustLib.instance.api.crateApiTransfersDigestNew();

  Future<String> revision();

  /// Await each update in source order. Each chunk may contain at most 64 KiB.
  Future<void> update({required List<int> bytes});
}
