// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'api/connection.dart';
import 'api/overview.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `check`, `error`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `drop`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Controller>>
abstract class Controller implements RustOpaqueInterface {
  Future<void> close();

  Future<Connection> connect({required String address});

  Future<void> markNotificationRead({required String id});

  Future<void> markNotificationsRead();

  /// Notify on foreground resume or a platform connectivity callback.
  Future<void> networkChanged();

  /// Read notifications received through this controller's active subscriptions.
  Future<String> notifications();

  static Future<Controller> open({
    required String path,
    required bool internet,
    required List<String> relays,
  }) => RustLib.instance.api.crateApiControllerOpen(
    path: path,
    internet: internet,
    relays: relays,
  );

  Future<String> pair({required String ticket});

  Future<String> pairPin({required String origin, required String pin});

  Future<List<String>> peers();

  Future<void> setName({required String name});

  Future<OverviewUpdates> watchUsage({
    required List<String> addresses,
    required String query,
  });
}
