use super::*;

fn source(fixture: &Fixture, code: &str) {
    let root = fixture.root.join("package");
    std::fs::create_dir_all(root.join("dev.sailry.platform/host")).unwrap();
    let manifest = include_str!("../../../../../../plugins/commands/plugin.json");
    std::fs::write(root.join("plugin.json"), manifest).unwrap();
    let manifest: Value = serde_json::from_str(manifest).unwrap();
    let source = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../../plugins/commands");
    let extension = &manifest["extensions"]["dev.sailry.platform"];
    for resource in ["desktop", "host"]
        .into_iter()
        .flat_map(|section| extension[section]["resources"].as_array().unwrap())
    {
        let path = resource.as_str().unwrap();
        let target = root.join(path);
        std::fs::create_dir_all(target.parent().unwrap()).unwrap();
        std::fs::copy(source.join(path), target).unwrap();
    }
    std::fs::write(root.join("dev.sailry.platform/host/main.js"), code).unwrap();
}

async fn update(fixture: &Fixture, revision: u64) -> plugin::Info {
    let Output::Plugin(info) = execute(
        fixture,
        Command::InstallPlugin {
            name: "commands".into(),
            path: "package".into(),
            worktree: fixture.session.worktree,
            expected_revision: revision,
        },
    )
    .await
    else {
        panic!()
    };
    assert!(info.issues.is_empty(), "{:?}", info.issues);
    info
}

#[tokio::test]
async fn preserves_frozen_transforms_and_known_results() {
    for remote in [false, true] {
        let server = Server::tools(vec![(
            name("run_command"),
            json!({"command":"printf original >> once.txt"}),
        )])
        .await;
        let mut fixture = Fixture::new(remote, &server).await;
        package(&fixture).await;
        let original =
            include_str!("../../../../../../plugins/commands/dev.sailry.platform/host/main.js");
        source(
            &fixture,
            &original.replace(
                "export function result({ output }) {",
                "export function result({ output }) { throw new Error('Presentation failed');",
            ),
        );
        let old = update(&fixture, 1).await;
        planning::configure(&mut fixture, WorkMode::Code).await;
        let Output::QueuedTurn(turn) = execute(
            &fixture,
            Command::QueueTurn {
                session: fixture.session.id,
                expected_revision: fixture.session.revision,
                message: "Run the requested command".into(),
            },
        )
        .await
        else {
            panic!()
        };
        assert!(turn.plugins.contains(&old.summary.reference()));
        source(
            &fixture,
            &original.replace(
                "return { command, cwd",
                "return { command: 'touch changed.txt', cwd",
            ),
        );
        update(&fixture, 2).await;
        execute(
            &fixture,
            Command::SetPluginEnabled {
                name: "commands".into(),
                expected_revision: 3,
                enabled: false,
            },
        )
        .await;
        execute(
            &fixture,
            Command::RemovePlugin {
                name: "commands".into(),
                expected_revision: 4,
            },
        )
        .await;
        execute(&fixture, Command::StartQueuedTurn { turn: turn.id }).await;
        let page = finished(&fixture.client, fixture.session.id, turn.id).await;
        let result = results(&page);
        assert_eq!(result.len(), 1);
        assert_eq!(result[0]["output"]["kind"], "command_result", "{page:?}");
        assert_eq!(
            result[0]["output"]["data"]["outcome"],
            json!({"kind":"exited","data":0})
        );
        // The VM reports engine errors without evaluating arbitrary thrown objects.
        assert_eq!(
            result[0]["presentation_error"],
            "tool.internal: plugin JavaScript execution failed: Exception generated by QuickJS"
        );
        assert_eq!(
            std::fs::read_to_string(fixture.root.join("once.txt")).unwrap(),
            "original"
        );
        assert!(!fixture.root.join("changed.txt").exists());
        let profile = fixture.node.profile().to_owned();
        fixture.node.shutdown().await.unwrap();
        let node = Node::start(profile).await.unwrap();
        let client = Client::new(if remote {
            fixture.controller.handle().remote(node.link().address())
        } else {
            node.local()
        });
        assert_eq!(history(&client, fixture.session.id).await, page);
        let Output::Plugins(packages) = client
            .execute(client.prepare(Command::ListPlugins))
            .await
            .unwrap()
        else {
            panic!()
        };
        assert!(!packages.iter().any(|package| package.name == "commands"));
        assert_eq!(
            std::fs::read_to_string(fixture.root.join("once.txt")).unwrap(),
            "original"
        );
        node.shutdown().await.unwrap();
        fixture.controller.close().await.unwrap();
    }
}

#[tokio::test]
async fn waiting_releases_vm_capacity() {
    for remote in [false, true] {
        let server = Server::tools(vec![(
            name("run_command"),
            json!({"command":"sleep 60 & task_pid=$!; printf '%s' \"$task_pid\" > child.pid; printf started > running.txt; wait \"$task_pid\""}),
        )])
        .await;
        let fixture = Fixture::new(remote, &server).await;
        let info = package(&fixture).await;
        let other_root = fixture.directory.path().join("other");
        std::fs::create_dir(&other_root).unwrap();
        let other = approvals::prepare(&fixture.client, &server, &other_root).await;
        let mut running = Vec::new();
        for session in [fixture.session.id, other.id] {
            let turn = approvals::submit(&fixture.client, session).await;
            let (_, approval) = approvals::pending(&fixture.client, session).await;
            process::decide(&fixture.client, &approval, Decision::Approve).await;
            running.push((session, turn));
        }
        tokio::time::timeout(Duration::from_secs(5), async {
            while !fixture.root.join("running.txt").exists()
                || !other_root.join("running.txt").exists()
            {
                tokio::time::sleep(Duration::from_millis(10)).await;
            }
        })
        .await
        .unwrap();
        let children: Vec<i32> = [&fixture.root, &other_root]
            .into_iter()
            .map(|root| {
                std::fs::read_to_string(root.join("child.pid"))
                    .unwrap()
                    .parse()
                    .unwrap()
            })
            .collect();
        // Both foreground processes are running. A third, ordinary JS callback must still run.
        let request = fixture
            .client
            .prepare(Command::CallPlugin {
                handler: "read".into(),
                input: json!({}),
            })
            .with_plugin(scope(&fixture, &info));
        let response =
            tokio::time::timeout(Duration::from_secs(5), fixture.client.execute(request))
                .await
                .expect("process waits exhausted the VM pool")
                .unwrap();
        assert_eq!(response, Output::PluginResult(json!({})));
        for (session, turn) in running {
            execute(&fixture, Command::StopTurn { turn }).await;
            let page = finished(&fixture.client, session, turn).await;
            assert_eq!(page.runs.last().unwrap().status, Status::Cancelled);
        }
        // Node shutdown joins process cleanup; no long-lived fixture commands survive it.
        tokio::time::timeout(Duration::from_secs(5), fixture.node.shutdown())
            .await
            .unwrap()
            .unwrap();
        tokio::time::timeout(Duration::from_secs(3), async {
            for child in children {
                // Probe only the exact isolated fixture child; never signal unrelated processes.
                while unsafe { libc::kill(child, 0) } == 0 {
                    tokio::time::sleep(Duration::from_millis(10)).await;
                }
            }
        })
        .await
        .expect("cancelled command left a running child");
        fixture.controller.close().await.unwrap();
    }
}
