// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `new`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Upload>>
abstract class Upload implements RustOpaqueInterface {
  Future<void> close();

  /// Signal EOF and await the shared Client's complete size/hash verification.
  /// Then submit FinishAttachmentUpload with one retained durable request ID.
  Future<void> finish();

  /// Await each write in source order. Accepted bytes are not yet verified or published.
  Future<void> write({required List<int> bytes});
}
